global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PRISM 오케스트레이션 에이전트 메트릭스 (현재 비활성화 - 실제 서비스가 없음)
  # - job_name: 'prism-orchestration'
  #   static_configs:
  #     - targets: ['localhost:8000']
  #   scrape_interval: 5s
  #   metrics_path: /metrics

  # PostgreSQL 메트릭스 (postgres_exporter 필요 - 현재 비활성화)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['localhost:9187']
  #   scrape_interval: 30s

  # Redis 메트릭스 (redis_exporter 필요 - 현재 비활성화)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['localhost:9121']
  #   scrape_interval: 30s

  # Kafka 메트릭스 (kafka_exporter 필요 - 현재 비활성화)
  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['localhost:9308']
  #   scrape_interval: 30s

  # AI 에이전트 개별 메트릭스 (현재 비활성화 - 실제 서비스가 없음)
  # - job_name: 'monitoring-agent'
  #   static_configs:
  #     - targets: ['localhost:8001']
  #   scrape_interval: 10s

  # - job_name: 'prediction-agent'
  #   static_configs:
  #     - targets: ['localhost:8002']
  #   scrape_interval: 10s

  # - job_name: 'control-agent'
  #   static_configs:
  #     - targets: ['localhost:8003']
  #   scrape_interval: 10s