[project]
name = "prism-orch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kafka-python==2.0.2",
    "psycopg2-binary==2.9.7",
    "redis==5.0.1",
    "requests>=2.32.4",
    "weaviate-client==4.4.0",
]
